// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebMVC_Hanhkhach_Chuyenbay.Data;

#nullable disable

namespace WebMVC_Hanhkhach_Chuyenbay.Migrations
{
    [DbContext(typeof(WebMVC_Hanhkhach_ChuyenbayContext))]
    partial class WebMVC_Hanhkhach_ChuyenbayContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebMVC_Hanhkhach_Chuyenbay.Models.ChuyenBay", b =>
                {
                    b.Property<int>("MaChuyenBay")
                        .HasColumnType("int");

                    b.Property<decimal>("GiaVe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaHanhKhach")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBay")
                        .HasColumnType("datetime2");

                    b.HasKey("MaChuyenBay");

                    b.HasIndex("MaHanhKhach");

                    b.ToTable("ChuyenBay");

                    b.HasData(
                        new
                        {
                            MaChuyenBay = 1,
                            GiaVe = 1000000m,
                            MaHanhKhach = 1,
                            NgayBay = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaChuyenBay = 4,
                            GiaVe = 1000000m,
                            MaHanhKhach = 1,
                            NgayBay = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaChuyenBay = 2,
                            GiaVe = 1500000m,
                            MaHanhKhach = 2,
                            NgayBay = new DateTime(2023, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaChuyenBay = 5,
                            GiaVe = 1500000m,
                            MaHanhKhach = 2,
                            NgayBay = new DateTime(2023, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaChuyenBay = 3,
                            GiaVe = 2000000m,
                            MaHanhKhach = 3,
                            NgayBay = new DateTime(2023, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaChuyenBay = 6,
                            GiaVe = 2000000m,
                            MaHanhKhach = 3,
                            NgayBay = new DateTime(2023, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("WebMVC_Hanhkhach_Chuyenbay.Models.HanhKhach", b =>
                {
                    b.Property<int>("MaHanhKhach")
                        .HasColumnType("int");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoCMND")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHanhKhach");

                    b.ToTable("HanhKhach");

                    b.HasData(
                        new
                        {
                            MaHanhKhach = 1,
                            HoTen = "Nguyen Van A",
                            NoiDen = "Hanoi",
                            SoCMND = "123456789",
                            SoDT = "0987654321"
                        },
                        new
                        {
                            MaHanhKhach = 2,
                            HoTen = "Tran Thi B",
                            NoiDen = "Ho Chi Minh City",
                            SoCMND = "987654321",
                            SoDT = "0123456789"
                        },
                        new
                        {
                            MaHanhKhach = 3,
                            HoTen = "Le Van C",
                            NoiDen = "Da Nang",
                            SoCMND = "456789123",
                            SoDT = "1234567890"
                        });
                });

            modelBuilder.Entity("WebMVC_Hanhkhach_Chuyenbay.Models.ChuyenBay", b =>
                {
                    b.HasOne("WebMVC_Hanhkhach_Chuyenbay.Models.HanhKhach", "HanhKhach")
                        .WithMany("ChuyenBays")
                        .HasForeignKey("MaHanhKhach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HanhKhach");
                });

            modelBuilder.Entity("WebMVC_Hanhkhach_Chuyenbay.Models.HanhKhach", b =>
                {
                    b.Navigation("ChuyenBays");
                });
#pragma warning restore 612, 618
        }
    }
}
