// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WinForm_Khambenh.Data;

#nullable disable

namespace WinForm_Khambenh.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WinForm_Khambenh.Model.HoSoKhamBenh", b =>
                {
                    b.Property<int>("MaHoSo")
                        .HasColumnType("int");

                    b.Property<bool>("CapCuu")
                        .HasColumnType("bit");

                    b.Property<string>("KhoaKham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiBenh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaBenhNhan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayKham")
                        .HasColumnType("datetime2");

                    b.HasKey("MaHoSo");

                    b.ToTable("HoSoKhamBenhs");

                    b.HasData(
                        new
                        {
                            MaHoSo = 1,
                            CapCuu = false,
                            KhoaKham = "Nội tổng quát",
                            LoaiBenh = "Cảm cúm",
                            MaBenhNhan = 101,
                            NgayKham = new DateTime(2025, 6, 20, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            MaHoSo = 2,
                            CapCuu = true,
                            KhoaKham = "Ngoại chấn thương",
                            LoaiBenh = "Gãy tay",
                            MaBenhNhan = 102,
                            NgayKham = new DateTime(2025, 6, 21, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            MaHoSo = 3,
                            CapCuu = false,
                            KhoaKham = "Tai mũi họng",
                            LoaiBenh = "Viêm họng",
                            MaBenhNhan = 103,
                            NgayKham = new DateTime(2025, 6, 22, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
